[input]
type="dir"
path = "/vast/projects/RCP/pea_DNA_sample"


[[modules]]
use="/stornext/System/data/modulefiles/nvidia"
name="guppy-gpu/6.2.1"

[output]
path = "/vast/scratch/users/yang.e/guppy-benchmarkme" 

[jobs]
cmd="guppy_basecaller -i pea_DNA_sample --num_callers ${num_callers} -x 'cuda:all' -c ${model} -s pea_DNA_sample_basecalled --chunks_per_runner ${chunks_per_runner}"
num_reps = 1 
params_path = "/vast/scratch/users/yang.e/ToolParametriser/examples/ONTGuppy-profile-fullscan.csv" 
tool_type="guppy"
run_type=""
email=""
qos="bonus"

[[cmd_placeholder]]
name="model"
path="dna_r10.4.1_e8.2_400bps_sup.cfg"
